BASECLASSDIR='/opt/classes'
ASPENCLASSDIR='/opt/aspenos/classes'
CLASSPATH=$BASECLASSDIR

CLASSPATH=$CLASSPATH:$BASECLASSDIR/mail.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/activation.jar

CLASSPATH=$CLASSPATH:$BASECLASSDIR/jdbc6.5-1.2.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/postgresql.jar
#CLASSPATH=$CLASSPATH:$BASECLASSDIR/jsdk.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/jsdk22.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/resin.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/ssl.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/ApacheJServ.jar

CLASSPATH=$CLASSPATH:$BASECLASSDIR/xerces.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/jaxp.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/xt.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/xml.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/xp.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/parser.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/xmlclass.jar

CLASSPATH=$CLASSPATH:$BASECLASSDIR/x509v1.jar
CLASSPATH=$CLASSPATH:$BASECLASSDIR/MOCHA.ZIP
#CLASSPATH=$CLASSPATH:/opt/jdk117_v3/lib/classes.zip

ASPENCLASSPATH=$ASPENCLASSDIR:$CLASSPATH


java -classpath $ASPENCLASSPATH -Djdbc.drivers=postgresql.Driver org.aspenos.util.appinstall.RunAppInstaller config/cmd_line_install.properties
